version: '3.2'
services:
  mysql-server:
    container_name: mysql-trial
    ports:
      - "13302:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: secret
    image: mysql/mysql-server

  wordpress:
    image: wordpress:latest
    container_name: wordpress-trial
    ports:
      - "20082:80"
    environment:
      WORDPRESS_DB_HOST: mysql-server:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: secret
    depends_on:
      - mysql-server 
  
  grafana:
    image: grafana/grafana
    container_name: grafana-trial
    ports:
      - "3001:3000"